version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: carpitan_production
      POSTGRES_USER: carpitan
      POSTGRES_PASSWORD: secretpassword

  redis:
    image: redis:6.0
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://carpitan:secretpassword@db/carpitan_production
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
      SECRET_KEY_BASE: 6827dd5abe45cab422d288c0723e8e761a042051dd417b475d01e1eda531c05411ea8911522c8a94057a23e364ec31944d6fc5a402fc1fec8c11c011ce53cedb
      ASSUME_SSL: 'false'
      FORCE_SSL: 'false'
    entrypoint: ["./bin/docker-entrypoint"]

  hansard_report:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd /rails/HansardReport/hansard-report && exec uvicorn app.server:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    depends_on:
      - web
    environment:
      RAILS_ENV: production

volumes:
  postgres_data:
  redis_data:
